GET http://localhost:3000/api/car?include=_count,captures,violations
###
POST http://localhost:3000/api/capture
Content-Type: application/json

{
    "location":"Location A",
    "car":{
        "connectOrCreate":{
            "where":{
                "licensePlate":"97842-D-30"
            },
            "create":{
                "licensePlate":"97842-D-30"
            }
        }
    }
}

###
POST http://localhost:3000/api/violation

###